/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AlmidonTapia
 */
public class JFrame_login extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Inicio_login
     */
    public JFrame_login() {
        initComponents();
        this.setLocationRelativeTo(this); //Poner el JFrame en el centro de la pantalla
        this.getContentPane().setBackground(Color.white); //Color del JFrame
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bg = new javax.swing.JPanel();
        jPanel_Imagen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Form = new javax.swing.JPanel();
        jLabel_Bienvenida = new javax.swing.JLabel();
        jLabel_DescBienvenida = new javax.swing.JLabel();
        jLabel_NombreUsuario = new javax.swing.JLabel();
        jSeparator_Usuario_label_Textfield = new javax.swing.JSeparator();
        jSeparator_Password_label_Textfield = new javax.swing.JSeparator();
        jTextField_NombreUsuario = new javax.swing.JTextField();
        jButton_IniciarSesion = new javax.swing.JButton();
        jLabel_Contraseña = new javax.swing.JLabel();
        jCheckBox_RecuperaCredenciales = new javax.swing.JCheckBox();
        jPasswordField_Contraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_bg.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_bg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Imagen.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/big-shopping-sale.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel_Imagen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 470, 550));

        jPanel_bg.add(jPanel_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 550));

        jPanel_Form.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Bienvenida.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel_Bienvenida.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Bienvenida.setText("Bienvenido a Minimarket");
        jPanel_Form.add(jLabel_Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 41));

        jLabel_DescBienvenida.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_DescBienvenida.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_DescBienvenida.setText("Inicia sesion para acceder al sistema");
        jPanel_Form.add(jLabel_DescBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel_NombreUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_NombreUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_NombreUsuario.setText("Usuario");
        jPanel_Form.add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jSeparator_Usuario_label_Textfield.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator_Usuario_label_Textfield.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_Form.add(jSeparator_Usuario_label_Textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 340, 10));

        jSeparator_Password_label_Textfield.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator_Password_label_Textfield.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_Form.add(jSeparator_Password_label_Textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 340, 10));

        jTextField_NombreUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_NombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_NombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_NombreUsuario.setText("Ingrese su nombre de usuario");
        jTextField_NombreUsuario.setAutoscrolls(false);
        jTextField_NombreUsuario.setBorder(null);
        jTextField_NombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_NombreUsuarioMousePressed(evt);
            }
        });
        jPanel_Form.add(jTextField_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 344, 40));

        jButton_IniciarSesion.setBackground(new java.awt.Color(84, 197, 65));
        jButton_IniciarSesion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_IniciarSesion.setForeground(new java.awt.Color(244, 238, 241));
        jButton_IniciarSesion.setText("Iniciar sesion");
        jButton_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_IniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_IniciarSesionMouseExited(evt);
            }
        });
        jButton_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IniciarSesionActionPerformed(evt);
            }
        });
        jPanel_Form.add(jButton_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 367, 344, 41));

        jLabel_Contraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Contraseña.setText("Contraseña");
        jPanel_Form.add(jLabel_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jCheckBox_RecuperaCredenciales.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox_RecuperaCredenciales.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jCheckBox_RecuperaCredenciales.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox_RecuperaCredenciales.setText("Olvidaste tus credenciales");
        jPanel_Form.add(jCheckBox_RecuperaCredenciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jPasswordField_Contraseña.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField_Contraseña.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Contraseña.setText("********");
        jPasswordField_Contraseña.setBorder(null);
        jPanel_Form.add(jPasswordField_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nuevo usuario");
        jPanel_Form.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jPanel_bg.add(jPanel_Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 540, 550));

        getContentPane().add(jPanel_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IniciarSesionActionPerformed
        // iniciar sesion code
        if(!String.valueOf(jPasswordField_Contraseña.getPassword()).isEmpty() || !String.valueOf(jTextField_NombreUsuario.getText()).isEmpty()){
            JOptionPane.showMessageDialog(this, "Falta compeltar los campos", "ERROR", JOptionPane.WARNING_MESSAGE);
  
        }else{
            JOptionPane.showMessageDialog(this, "Login Exitoso \nUsuario: "+jTextField_NombreUsuario.getText() +  "\nContraseña: "+String.valueOf(jPasswordField_Contraseña.getPassword()),"LOGIN",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jButton_IniciarSesionActionPerformed

    private void jButton_IniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IniciarSesionMouseEntered
        jButton_IniciarSesion.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jButton_IniciarSesionMouseEntered

    private void jButton_IniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IniciarSesionMouseExited
        jButton_IniciarSesion.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jButton_IniciarSesionMouseExited

    private void jTextField_NombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_NombreUsuarioMousePressed
        
        if(jTextField_NombreUsuario.getText().equals("Ingrese su nombre de usuario")){
           jTextField_NombreUsuario.setText((""));
           jTextField_NombreUsuario.setForeground(Color.black);
        }
        if(String.valueOf(jPasswordField_Contraseña.getPassword()).isEmpty()){
            jPasswordField_Contraseña.setText("********");
            jPasswordField_Contraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_NombreUsuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_IniciarSesion;
    private javax.swing.JCheckBox jCheckBox_RecuperaCredenciales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Bienvenida;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_DescBienvenida;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JPanel jPanel_Form;
    private javax.swing.JPanel jPanel_Imagen;
    private javax.swing.JPanel jPanel_bg;
    private javax.swing.JPasswordField jPasswordField_Contraseña;
    private javax.swing.JSeparator jSeparator_Password_label_Textfield;
    private javax.swing.JSeparator jSeparator_Usuario_label_Textfield;
    private javax.swing.JTextField jTextField_NombreUsuario;
    // End of variables declaration//GEN-END:variables
}
