/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author AlmidonTapia
 */
public class JFrame_Provedores extends javax.swing.JFrame {

    /**
     * Creates new form JFrameProvedores
     */
    public JFrame_Provedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_bg = new javax.swing.JPanel();
        jPanel_Nav = new javax.swing.JPanel();
        jLabel_ModuloClientes = new javax.swing.JLabel();
        jLabel_ModuloProducto = new javax.swing.JLabel();
        jLabel_ModuloVentas = new javax.swing.JLabel();
        jLabel_ModuloReportes = new javax.swing.JLabel();
        jLabel_Modulo_Comprobantes = new javax.swing.JLabel();
        jButton_Salir = new javax.swing.JButton();
        jLabel_UserIcon = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel_Modulo_Comprobantes1 = new javax.swing.JLabel();
        jLabel_NombreEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Productos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_bg.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Nav.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_Nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ModuloClientes.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloClientes.setText("Clientes");
        jPanel_Nav.add(jLabel_ModuloClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 165, -1, -1));

        jLabel_ModuloProducto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloProducto.setText("Productos");
        jPanel_Nav.add(jLabel_ModuloProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 198, -1, -1));

        jLabel_ModuloVentas.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloVentas.setText("Ventas");
        jPanel_Nav.add(jLabel_ModuloVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 231, -1, -1));

        jLabel_ModuloReportes.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloReportes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloReportes.setText("Reportes");
        jPanel_Nav.add(jLabel_ModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 264, -1, -1));

        jLabel_Modulo_Comprobantes.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_Modulo_Comprobantes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Modulo_Comprobantes.setText("Provedores");
        jPanel_Nav.add(jLabel_Modulo_Comprobantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jButton_Salir.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salir.setText("Salir");
        jPanel_Nav.add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 480, 160, 35));

        jLabel_UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user_149071.png"))); // NOI18N
        jPanel_Nav.add(jLabel_UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 20, 30));

        jLabel_UserName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_UserName.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_UserName.setText("Saul Tapia Almidon");
        jPanel_Nav.add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel_Modulo_Comprobantes1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_Modulo_Comprobantes1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Modulo_Comprobantes1.setText("Comprobantes");
        jPanel_Nav.add(jLabel_Modulo_Comprobantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 297, -1, -1));

        jLabel_NombreEmpresa.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel_NombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombreEmpresa.setText("Minimarket");
        jPanel_Nav.add(jLabel_NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 143, 27));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/store.png"))); // NOI18N
        jPanel_Nav.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 90));

        jPanel_bg.add(jPanel_Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 560));

        jPanel_Productos.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Productos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel_Productos.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 260, 50));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Observacion");
        jPanel_Productos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 80, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/editar.png"))); // NOI18N
        jLabel3.setText("Ingreso de más Productos");
        jPanel_Productos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 280, 40));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Codigo");
        jPanel_Productos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 20));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("0.00");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel_Productos.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 110, 40));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre");
        jPanel_Productos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, 20));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("ingrese provedor");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel_Productos.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 300, 40));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione categoria-", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        jPanel_Productos.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 240, 40));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Precio");
        jPanel_Productos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 80, 20));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("ingrese nombre del producto");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel_Productos.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 300, 40));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Categoria");
        jPanel_Productos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 80, 20));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setActionCommand("<Not Set>");
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel_Productos.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 600, 130));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Proveedor");
        jPanel_Productos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, 20));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Stock");
        jPanel_Productos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 80, 20));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("ingrese id del producto");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel_Productos.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 170, 40));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("0.00");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel_Productos.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 120, 40));

        jPanel_bg.add(jPanel_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 760, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_ModuloClientes;
    private javax.swing.JLabel jLabel_ModuloProducto;
    private javax.swing.JLabel jLabel_ModuloReportes;
    private javax.swing.JLabel jLabel_ModuloVentas;
    private javax.swing.JLabel jLabel_Modulo_Comprobantes;
    private javax.swing.JLabel jLabel_Modulo_Comprobantes1;
    private javax.swing.JLabel jLabel_NombreEmpresa;
    private javax.swing.JLabel jLabel_UserIcon;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JPanel jPanel_Nav;
    private javax.swing.JPanel jPanel_Productos;
    private javax.swing.JPanel jPanel_bg;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
