/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author AlmidonTapia
 */
public class JFrame_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_MenuPrincipal
     */
    public JFrame_MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this); //Poner el JFrame en el centro de la pantalla
        this.getContentPane().setBackground(Color.white); //Color del JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Bg = new javax.swing.JPanel();
        jPanel_Nav = new javax.swing.JPanel();
        jLabel_NombreEmpresa = new javax.swing.JLabel();
        jLabel_ModuloClientes = new javax.swing.JLabel();
        jLabel_ModuloProducto = new javax.swing.JLabel();
        jLabel_ModuloVentas = new javax.swing.JLabel();
        jLabel_ModuloReportes = new javax.swing.JLabel();
        jLabel_Modulo_Comprobantes = new javax.swing.JLabel();
        jButton_Salir = new javax.swing.JButton();
        jLabel_UserIcon = new javax.swing.JLabel();
        jLabel_UserName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Sections = new javax.swing.JPanel();
        jPanel_ModReportes = new javax.swing.JPanel();
        jLabe_l_TitleReportes = new javax.swing.JLabel();
        jButton_Reportes = new javax.swing.JButton();
        jLabel_ImgModReportes = new javax.swing.JLabel();
        jPanel_ModClientes = new javax.swing.JPanel();
        jLabel_TitleClientes = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jLabel_ImgModClientes = new javax.swing.JLabel();
        jPanel_ModProductos = new javax.swing.JPanel();
        jLabel_TitleProductos = new javax.swing.JLabel();
        jButton_Productos = new javax.swing.JButton();
        jLabel_ImgModProductos = new javax.swing.JLabel();
        jPanel_ModVentas = new javax.swing.JPanel();
        jLabel_TitleVentas = new javax.swing.JLabel();
        jButton_Ventas = new javax.swing.JButton();
        jLabel_ImgModVentas = new javax.swing.JLabel();
        jPanel_ModComprobantes = new javax.swing.JPanel();
        jLabel_ImgModComprobantes1 = new javax.swing.JLabel();
        jLabel_TitleComprobantes1 = new javax.swing.JLabel();
        jButton_Comprobantes1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_ImgModComprobantes = new javax.swing.JLabel();
        jLabel_TitleComprobantes = new javax.swing.JLabel();
        jButton_Comprobantes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);

        jPanel_Bg.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Nav.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_Nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreEmpresa.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel_NombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombreEmpresa.setText("Minimarket");
        jPanel_Nav.add(jLabel_NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 143, 27));

        jLabel_ModuloClientes.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloClientes.setText("Clientes");
        jPanel_Nav.add(jLabel_ModuloClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel_ModuloProducto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloProducto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloProducto.setText("Productos");
        jPanel_Nav.add(jLabel_ModuloProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel_ModuloVentas.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloVentas.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloVentas.setText("Ventas");
        jPanel_Nav.add(jLabel_ModuloVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel_ModuloReportes.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_ModuloReportes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ModuloReportes.setText("Reportes");
        jPanel_Nav.add(jLabel_ModuloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel_Modulo_Comprobantes.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel_Modulo_Comprobantes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Modulo_Comprobantes.setText("Comprobantes");
        jPanel_Nav.add(jLabel_Modulo_Comprobantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jButton_Salir.setBackground(new java.awt.Color(255, 0, 51));
        jButton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salir.setText("Salir");
        jPanel_Nav.add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 480, 160, 35));

        jLabel_UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/user_149071.png"))); // NOI18N
        jPanel_Nav.add(jLabel_UserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 20, 30));

        jLabel_UserName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel_UserName.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_UserName.setText("Saul Tapia Almidon");
        jPanel_Nav.add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/store.png"))); // NOI18N
        jPanel_Nav.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 90));

        jPanel_Bg.add(jPanel_Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        jPanel_Sections.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Sections.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_Sections.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_ModReportes.setBackground(new java.awt.Color(102, 204, 255));
        jPanel_ModReportes.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_ModReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabe_l_TitleReportes.setBackground(new java.awt.Color(51, 51, 51));
        jLabe_l_TitleReportes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabe_l_TitleReportes.setForeground(new java.awt.Color(51, 51, 51));
        jLabe_l_TitleReportes.setText("Reportes");
        jPanel_ModReportes.add(jLabe_l_TitleReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 154, -1, -1));

        jButton_Reportes.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Reportes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_Reportes.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Reportes.setText("Abrir Modulo");
        jPanel_ModReportes.add(jButton_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 177, 128, -1));

        jLabel_ImgModReportes.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_ImgModReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/report_2474248.png"))); // NOI18N
        jPanel_ModReportes.add(jLabel_ImgModReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel_Sections.add(jPanel_ModReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 170, 220));

        jPanel_ModClientes.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_ModClientes.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_ModClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TitleClientes.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_TitleClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TitleClientes.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_TitleClientes.setText("Clientes");
        jPanel_ModClientes.add(jLabel_TitleClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 154, -1, -1));

        jButtonClientes.setBackground(new java.awt.Color(51, 51, 51));
        jButtonClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClientes.setText("Abrir Modulo");
        jPanel_ModClientes.add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 177, 128, -1));

        jLabel_ImgModClientes.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_ImgModClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/clientespng.png"))); // NOI18N
        jPanel_ModClientes.add(jLabel_ImgModClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 14, -1, -1));

        jPanel_Sections.add(jPanel_ModClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 170, 220));

        jPanel_ModProductos.setBackground(new java.awt.Color(204, 255, 255));
        jPanel_ModProductos.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_ModProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TitleProductos.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_TitleProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TitleProductos.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_TitleProductos.setText("Productos");
        jPanel_ModProductos.add(jLabel_TitleProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 154, -1, -1));

        jButton_Productos.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Productos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_Productos.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Productos.setText("Abrir Modulo");
        jPanel_ModProductos.add(jButton_Productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 177, 125, -1));

        jLabel_ImgModProductos.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_ImgModProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/agregar-producto (3).png"))); // NOI18N
        jPanel_ModProductos.add(jLabel_ImgModProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 14, -1, -1));

        jPanel_Sections.add(jPanel_ModProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 170, 220));

        jPanel_ModVentas.setBackground(new java.awt.Color(255, 204, 153));
        jPanel_ModVentas.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_ModVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TitleVentas.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_TitleVentas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TitleVentas.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_TitleVentas.setText("Ventas");
        jPanel_ModVentas.add(jLabel_TitleVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 154, -1, -1));

        jButton_Ventas.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Ventas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_Ventas.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Ventas.setText("Abrir Modulo");
        jPanel_ModVentas.add(jButton_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 177, 125, -1));

        jLabel_ImgModVentas.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_ImgModVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/carrito-de-compras.png"))); // NOI18N
        jPanel_ModVentas.add(jLabel_ImgModVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, -1, 129));

        jPanel_Sections.add(jPanel_ModVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 170, 220));

        jPanel_ModComprobantes.setBackground(new java.awt.Color(255, 153, 255));
        jPanel_ModComprobantes.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_ModComprobantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ImgModComprobantes1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_ImgModComprobantes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/reportes.png"))); // NOI18N
        jPanel_ModComprobantes.add(jLabel_ImgModComprobantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 136, 134));

        jLabel_TitleComprobantes1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_TitleComprobantes1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TitleComprobantes1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_TitleComprobantes1.setText("Comprobantes");
        jPanel_ModComprobantes.add(jLabel_TitleComprobantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 153, -1, -1));

        jButton_Comprobantes1.setBackground(new java.awt.Color(51, 51, 51));
        jButton_Comprobantes1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_Comprobantes1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Comprobantes1.setText("Abrir Modulo");
        jPanel_ModComprobantes.add(jButton_Comprobantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, 125, -1));

        jPanel_Sections.add(jPanel_ModComprobantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 170, 220));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_ImgModComprobantes.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_ImgModComprobantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/personal.png"))); // NOI18N

        jLabel_TitleComprobantes.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_TitleComprobantes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TitleComprobantes.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TitleComprobantes.setText("Usuarios");

        jButton_Comprobantes.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Comprobantes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_Comprobantes.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Comprobantes.setText("Abrir Modulo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Comprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ImgModComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_TitleComprobantes)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel_ImgModComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_TitleComprobantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Comprobantes)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel_Sections.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 170, 220));

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("00:00:00");
        jPanel_Sections.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Fecha y Hora:");
        jPanel_Sections.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        jPanel_Bg.add(jPanel_Sections, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 730, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButton_Comprobantes;
    private javax.swing.JButton jButton_Comprobantes1;
    private javax.swing.JButton jButton_Productos;
    private javax.swing.JButton jButton_Reportes;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JButton jButton_Ventas;
    private javax.swing.JLabel jLabe_l_TitleReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_ImgModClientes;
    private javax.swing.JLabel jLabel_ImgModComprobantes;
    private javax.swing.JLabel jLabel_ImgModComprobantes1;
    private javax.swing.JLabel jLabel_ImgModProductos;
    private javax.swing.JLabel jLabel_ImgModReportes;
    private javax.swing.JLabel jLabel_ImgModVentas;
    private javax.swing.JLabel jLabel_ModuloClientes;
    private javax.swing.JLabel jLabel_ModuloProducto;
    private javax.swing.JLabel jLabel_ModuloReportes;
    private javax.swing.JLabel jLabel_ModuloVentas;
    private javax.swing.JLabel jLabel_Modulo_Comprobantes;
    private javax.swing.JLabel jLabel_NombreEmpresa;
    private javax.swing.JLabel jLabel_TitleClientes;
    private javax.swing.JLabel jLabel_TitleComprobantes;
    private javax.swing.JLabel jLabel_TitleComprobantes1;
    private javax.swing.JLabel jLabel_TitleProductos;
    private javax.swing.JLabel jLabel_TitleVentas;
    private javax.swing.JLabel jLabel_UserIcon;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Bg;
    private javax.swing.JPanel jPanel_ModClientes;
    private javax.swing.JPanel jPanel_ModComprobantes;
    private javax.swing.JPanel jPanel_ModProductos;
    private javax.swing.JPanel jPanel_ModReportes;
    private javax.swing.JPanel jPanel_ModVentas;
    private javax.swing.JPanel jPanel_Nav;
    private javax.swing.JPanel jPanel_Sections;
    // End of variables declaration//GEN-END:variables
}
